
############ LOGIN ############
# @name Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "gaby@gmail.com",
    "senha": "123456"
}

@TOKEN = {{Login.response.body.token}}


############ GET ALL COLORS ############
GET http://localhost:8080/cor

############ GET COLOR BY ID ############
GET http://localhost:8080/cor/1

############ CREATE NEW COLOR ############
POST http://localhost:8080/cor
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome": "Dourado"
}
