############ LOGIN ############
# @name Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "email": "gaby@gmail.com",
    "senha": "123456"
}

@TOKEN = {{Login.response.body.token}}


############################

############ GET ALL CUPOM DESCONTO ############
GET http://localhost:8080/cupomdesconto/list/1
Authorization: Bearer {{TOKEN}}


############ GET CUPOM DESCONTO BY ID ############
GET http://localhost:8080/cupomdesconto/1
Authorization: Bearer {{TOKEN}}

############ CREATE NEW CUPOM DESCONTO ############

POST http://localhost:8080/cupomdesconto
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "nome":"adsfadfa",
    "datafinal":"2026-12-12T11:11:00",
    "valorDesconto":12,
    "tipoCupomDesconto":1,
    "codigo":"asdfa",
    "valorMinimo":12
}

